try:
    print(lst[5])
except Exception as e:
    print(e.args)